
LATEX		= pdflatex

.SUFFIXES:	.pdf .tex

.tex.pdf :
	$(LATEX) $*.tex

TARGET=ChoosingAStatisticalTestToDiscernDistributions

all : ${TARGET}.pdf ${TARGET}-handout.pdf
	- rm -f ${TARGET}-handout.tex

${TARGET}-handout.tex : ${TARGET}.tex
	echo "%%" > ${TARGET}-handout.tex
	echo "%%" >> ${TARGET}-handout.tex
	echo "%%  DO NOT EDIT -- AUTOGENERATED FILE" >> ${TARGET}-handout.tex
	echo "%%  DO NOT EDIT -- AUTOGENERATED FILE" >> ${TARGET}-handout.tex
	echo "%%  DO NOT EDIT -- AUTOGENERATED FILE" >> ${TARGET}-handout.tex
	echo "%%  DO NOT EDIT -- AUTOGENERATED FILE" >> ${TARGET}-handout.tex
	echo "%%" >> ${TARGET}-handout.tex
	echo "%%" >> ${TARGET}-handout.tex
	sed -e 's/documentclass{beamer}/documentclass[handout]{beamer}/' \
				${TARGET}.tex >> ${TARGET}-handout.tex ; \

dummy :

clean :
	- rm -f ${TARGET}-handout.tex
	- rm -f *.dvi \
		*.aux \
		*.upa \
		*.log *.lot *.lof \
		*.bbl *.blg \
		*.ilg *.ind \
		*.idx *.toc *.tmp \
		*.nav *.snm \
		*.out \
		*.ps


spell :
	@for file in *.tex; \
	do \
	    echo "Running speller for $${file}"; \
	    ispell "$${file}"; \
	done

